---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/login":
    post:
      summary: login auth
      tags:
      - Login
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
  "/authors":
    get:
      summary: Get all authors
      tags:
      - Author
      responses:
        '200':
          description: successful
  "/books":
    get:
      summary: List all books
      tags:
      - Book
      responses:
        '200':
          description: successful
  "/books/search":
    get:
      summary: Search book by author or title name
      tags:
      - Book
      parameters:
      - name: searchTerm
        in: query
        description: term to search by book title or author name
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
  "/books/out-of-stock":
    get:
      summary: Get books that are out of stock
      tags:
      - Book
      responses:
        '200':
          description: successful
  "/books/{id}":
    parameters:
    - name: id
      in: path
      description: id of the book we want to get data for
      required: true
      schema:
        type: string
    get:
      summary: Get book by id
      tags:
      - Book
      responses:
        '200':
          description: successful
  "/loans":
    get:
      summary: list loans
      tags:
      - Loan
      responses:
        '200':
          description: successful
    post:
      summary: Create a new loan
      tags:
      - Loan
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                book_id:
                  type: string
                loan_duration:
                  type: integer
              required:
              - name
              - model
  "/loans/users/{user_id}":
    parameters:
    - name: user_id
      in: path
      description: user_id
      required: true
      schema:
        type: string
    get:
      summary: index_by_user loan
      tags:
      - Loan
      responses:
        '200':
          description: successful
  "/users":
    get:
      summary: list users
      responses:
        '200':
          description: successful
    post:
      summary: create user
      responses:
        '200':
          description: successful
  "/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      responses:
        '200':
          description: successful
    patch:
      summary: update user
      responses:
        '200':
          description: successful
    put:
      summary: update user
      responses:
        '200':
          description: successful
    delete:
      summary: delete user
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000/
